package com.pharmacare.inventory.data.local.entity

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Room Entity representing a Medical Equipment record in the database.
 *
 * Maps to the "equipment" table. Each field corresponds to a column.
 * The [equipmentId] is auto-generated by Room on insertion.
 *
 * @param equipmentId    Unique identifier (auto-incremented primary key).
 * @param equipmentName  Name of the equipment (e.g., "Blood Pressure Monitor").
 * @param category       Equipment category (e.g., "Diagnostic", "Surgical").
 * @param quantityInStock Current available stock count.
 * @param price          Unit price in the local currency.
 */
@Entity(tableName = "equipment")
data class Equipment(
    @PrimaryKey(autoGenerate = true)
    val equipmentId: Int = 0,

    val equipmentName: String,
    val category: String,
    val quantityInStock: Int,
    val price: Double
)
