package com.pharmacare.inventory.data.local.entity

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Room Entity representing a Medicine record in the database.
 *
 * Maps to the "medicines" table. Each field corresponds to a column.
 * The [medicineId] is auto-generated by Room on insertion.
 *
 * @param medicineId   Unique identifier (auto-incremented primary key).
 * @param medicineName Human-readable name of the medicine (e.g., "Amoxicillin 500mg").
 * @param category     Pharmacological category (e.g., "Antibiotic", "Painkiller").
 * @param expiryDate   Expiry date stored as a formatted string ("dd/MM/yyyy").
 * @param quantityInStock Current available stock count.
 * @param price        Unit price in the local currency.
 */
@Entity(tableName = "medicines")
data class Medicine(
    @PrimaryKey(autoGenerate = true)
    val medicineId: Int = 0,

    val medicineName: String,
    val category: String,
    val expiryDate: String,       // Stored as "dd/MM/yyyy" for human readability
    val quantityInStock: Int,
    val price: Double
)
